// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GameConstants
{
        public const string achievement_the_conqueror = "CgkIhcH_luQZEAIQBQ"; // <GPGSID>
        public const string leaderboard_fastest_completion_time_chapter_5__hard = "CgkIhcH_luQZEAIQEw"; // <GPGSID>
        public const string leaderboard_highest_level_achieved_easy = "CgkIhcH_luQZEAIQBg"; // <GPGSID>
        public const string leaderboard_highest_level_achieved_normal = "CgkIhcH_luQZEAIQBw"; // <GPGSID>
        public const string leaderboard_highest_level_achieved_hard = "CgkIhcH_luQZEAIQCA"; // <GPGSID>
        public const string leaderboard_fastest_completion_time_chapter_4__hard = "CgkIhcH_luQZEAIQEg"; // <GPGSID>
        public const string achievement_mini_maniac = "CgkIhcH_luQZEAIQAw"; // <GPGSID>
        public const string achievement_the_game_is_on = "CgkIhcH_luQZEAIQBA"; // <GPGSID>
        public const string achievement_i_am_zrexak_the_immortal = "CgkIhcH_luQZEAIQFQ"; // <GPGSID>
        public const string leaderboard_fastest_completion_time_chapter_6__hard = "CgkIhcH_luQZEAIQFA"; // <GPGSID>
        public const string leaderboard_fastest_completion_time_chapter_5__normal = "CgkIhcH_luQZEAIQDQ"; // <GPGSID>
        public const string leaderboard_fastest_completion_time_chapter_4__normal = "CgkIhcH_luQZEAIQDA"; // <GPGSID>
        public const string leaderboard_fastest_completion_time_chapter_3__normal = "CgkIhcH_luQZEAIQCw"; // <GPGSID>
        public const string leaderboard_fastest_completion_time_chapter_2__normal = "CgkIhcH_luQZEAIQCg"; // <GPGSID>
        public const string leaderboard_fastest_completion_time_chapter_1__normal = "CgkIhcH_luQZEAIQCQ"; // <GPGSID>
        public const string leaderboard_highest_level_achieved__no_damage_normal = "CgkIhcH_luQZEAIQFg"; // <GPGSID>
        public const string achievement_nohelp_droid = "CgkIhcH_luQZEAIQAg"; // <GPGSID>
        public const string leaderboard_fastest_completion_time_chapter_3__hard = "CgkIhcH_luQZEAIQEQ"; // <GPGSID>
        public const string leaderboard_fastest_completion_time_chapter_2__hard = "CgkIhcH_luQZEAIQEA"; // <GPGSID>
        public const string achievement_nk_coin_collector = "CgkIhcH_luQZEAIQAQ"; // <GPGSID>
        public const string leaderboard_highest_level_achieved__no_damage_hard = "CgkIhcH_luQZEAIQFw"; // <GPGSID>
        public const string leaderboard_fastest_completion_time_chapter_6__normal = "CgkIhcH_luQZEAIQDg"; // <GPGSID>
        public const string leaderboard_fastest_completion_time_chapter_1__hard = "CgkIhcH_luQZEAIQDw"; // <GPGSID>

}

